# Generated by Django 3.2.3 on 2021-05-21 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото')),
                ('title', models.CharField(max_length=124, verbose_name='Название номера')),
                ('desc', models.TextField(blank=True, max_length=500, verbose_name='Описание номера')),
                ('size', models.PositiveSmallIntegerField(verbose_name='Площадь номера')),
                ('smoke', models.BooleanField(default=True, verbose_name='Не курят')),
                ('num_people', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Кол-во спальных мест')),
                ('data_arrival', models.DateField(blank=True, default='', verbose_name='Дата заезда')),
                ('data_departure', models.DateField(blank=True, default='', verbose_name='Дата отъезде')),
            ],
        ),
    ]
