# Generated by Django 3.2.3 on 2021-05-21 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hotel', '0002_room_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='data_arrival',
            field=models.DateField(blank=True, verbose_name='Дата заезда'),
        ),
        migrations.AlterField(
            model_name='room',
            name='data_departure',
            field=models.DateField(blank=True, verbose_name='Дата отъезда'),
        ),
    ]
