# Generated by Django 3.2.3 on 2021-05-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0005_auto_20210521_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название удобства')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Иконка')),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='author',
        ),
        migrations.RemoveField(
            model_name='room',
            name='data_arrival',
        ),
        migrations.RemoveField(
            model_name='room',
            name='data_departure',
        ),
        migrations.AddField(
            model_name='room',
            name='facilities',
            field=models.ManyToManyField(to='Hotel.Facilities'),
        ),
    ]
