# Generated by Django 3.2.3 on 2021-05-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0006_auto_20210521_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilities',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название удобства'),
        ),
    ]
