# Generated by Django 3.2.3 on 2021-06-03 17:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название удобства')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Иконка')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
            ],
        ),
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Вид сервиса')),
                ('users', models.ManyToManyField(related_name='users_types', through='hotel.ServiceHotel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='servicehotel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typeservice', to='hotel.typeservice', verbose_name='Сервис'),
        ),
        migrations.AddField(
            model_name='servicehotel',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото')),
                ('title', models.CharField(max_length=60, verbose_name='Название номера')),
                ('desc', models.TextField(blank=True, max_length=500, verbose_name='Описание номера')),
                ('size', models.PositiveSmallIntegerField(verbose_name='Площадь номера')),
                ('smoke', models.BooleanField(default=True, verbose_name='Не курят')),
                ('price', models.PositiveSmallIntegerField(default=30, verbose_name='Цена за сутки')),
                ('num_people', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Кол-во спальных мест')),
                ('facilities', models.ManyToManyField(to='hotel.Facilities')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_rate', models.DecimalField(decimal_places=1, max_digits=3)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.typeservice')),
            ],
            options={
                'get_latest_by': ['date_avg_rate'],
            },
        ),
        migrations.CreateModel(
            name='BokkingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrival', models.DateField(verbose_name='Дата заезда')),
                ('date_departure', models.DateField(verbose_name='Дата отъезда')),
                ('date_order', models.DateField(auto_now_add=True, verbose_name='Дата заказа')),
                ('desc', models.CharField(max_length=124, verbose_name='Описание')),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_room', to='hotel.room')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='rate',
            constraint=models.CheckConstraint(check=models.Q(('avg_rate__gte', 0), ('avg_rate__lte', 10)), name='avg_rate_gte_lte'),
        ),
    ]
