# Generated by Django 3.2.3 on 2021-06-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bokkingroom',
            name='booking',
            field=models.BooleanField(default=False, verbose_name='Подтверждение брони'),
        ),
    ]
