# Generated by Django 3.2.3 on 2021-05-25 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BokkingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrival', models.DateField(verbose_name='Дата заезда')),
                ('date_departure', models.DateField(verbose_name='Дата отъезда')),
                ('date_order', models.DateField(auto_now_add=True, verbose_name='Дата заказа')),
                ('desc', models.CharField(max_length=124, verbose_name='Описание')),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_room', to='hotel.room')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
