# Generated by Django 3.2.3 on 2021-06-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_bokkingroom_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='number_room',
            field=models.CharField(default='0', max_length=3, verbose_name='№ комнаты'),
            preserve_default=False,
        ),
    ]
