# Generated by Django 3.2.3 on 2021-05-27 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_servicehotel_typeservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicehotel',
            name='mark',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
    ]
