# Generated by Django 3.2.3 on 2021-05-30 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0005_alter_typeservice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeservice',
            name='users',
            field=models.ManyToManyField(through='hotel.ServiceHotel', to=settings.AUTH_USER_MODEL),
        ),
    ]
