# Generated by Django 3.2.3 on 2021-05-30 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_typeservice_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicehotel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typeservice', to='hotel.typeservice', verbose_name='Сервис'),
        ),
    ]
